### ISSUE TITLE
Serving on different ports

### ISSUE THREAD

**Issue by fetimo** [chemoish/react-universal-tutorial#11]
Hi @chemoish, what's the reason for serving client content on one port and the server-related bits on another?

**Comment by chemoish** [comment]
@fetimo, I am not entirely sure if you need to manage them separately, BUT both the client and the server have different needs. Those needs surface in the webpack configuration, which cannot entirely be shared.

You can give it a try, I remember I had issues leveraging `webpack-dev-middleware` separately, but I don't recall exactly why. I also tried to follow the existing documentation (article, starter kits, main repos, etc.) out there and simplified the webpack configuration where I could.

_webpack is hella confusing—second is HMR and its brokenness—third is isomorphic + local CSS_
